In [2]:
import numpy as np

### Exercise 4

1. create a null vector / 1D array of size 10 and update fifth index to 11.

In [118]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [120]:
x[6] = 11

In [121]:
x

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

2. Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays

In [126]:
x = np.arange(1, 7)
x

array([1, 2, 3, 4, 5, 6])

In [128]:
y = np.reshape(x,(2,3)) # 2 x 3
y

array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
z = np.reshape(x,(3,2))
z

array([[1, 2],
       [3, 4],
       [5, 6]])

3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.
![](image/lat1.png)

In [4]:
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

4. Take a look at the following matrix. Access the [2, 1,1]

In [115]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])


In [116]:
s = z[2,1,1] # [row, kolom, dept]
s

2

### Assignment

1. Create a 4x4 matrix with values ranging from 0 to 3.\
(The following image is just as an example. It doesn't represent the real image of arrays in the question)
![](image/assignment2.png)

In [52]:
my_array = np.zeros((4,4))
my_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
e = np.arange(4)
t = e + my_array
t

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.\
![](image/assignment.png)

In [113]:
x = np.arange(0, 16).reshape(4, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [114]:
y = np.hsplit(x, 2)
y

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]